### ISSUE TITLE
Wdym with titans

### ISSUE THREAD

**Issue by jennocool** [ElementalMinecraftGaming/StableMythicWarriors#1]

**Comment by ElementalMinecraftGaming** [comment]
To use titans you need a MobAPI, it is usable without the API but titans won't be available.
The titans are basically mobs that have been edited with the titan command.

**Comment by ElementalMinecraftGaming** [comment]
There we go. 🙂
Enjoy the plugin.

**Comment by ElementalMinecraftGaming** [comment]
Issue solved
