### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TetroYT** [ElementalMinecraftGaming/StableMythicWarriors#2]
Can you make a tutorial or make it more easily known of how to create races/titans/characters etc ive done literally everything it says for how to make a race and it just keeps on saying set a race, health hunger etc

**Comment by TetroYT** [comment]
![4A3C419A-BA2F-490C-B1A8-BEF08DCE1966](https://user-images.githubusercontent.com/49662383/74686592-e6c26f80-51c9-11ea-9525-10883ac3a21f.png)
![D3818161-DFE8-4649-9558-56C5E662C2BB](https://user-images.githubusercontent.com/49662383/74686597-ea55f680-51c9-11ea-99b9-7e2680554471.png)

**Comment by ElementalMinecraftGaming** [comment]
Sorry for this issue, I will take a look at what may be causing it

**Comment by ElementalMinecraftGaming** [comment]
Sorry for the inconvenience @TetroYT here is a link to the fixed file.
https://github.com/ElementalMinecraftGaming/StableMythicWarriors/releases/download/1.0.1/StableMythicWarriors_dev-9.phar

**Comment by ElementalMinecraftGaming** [comment]
Sorry, i am working on a working release right now, thank you for getting in touch.

**Comment by ElementalMinecraftGaming** [comment]
Here is a working version: https://poggit.pmmp.io/r/76450/StableMythicWarriors_dev-10.phar
